unit CommDemo.Defines;

interface

const

{$IFDEF ENABLE_AUTH}
  ENABLE_AUTH = True;
{$ELSE}
  ENABLE_AUTH = False;
{$ENDIF}
{$IFDEF ENABLE_SUPPORT_SIGNAL}
  ENABLE_SUPPORT_SIGNAL = True;
{$ELSE}
  ENABLE_SUPPORT_SIGNAL = False;
{$ENDIF}
{$IFDEF ENABLE_DEBUG_MODE}
  ENABLE_DEBUG_MODE = True;
{$ELSE}
  ENABLE_DEBUG_MODE = False;
{$ENDIF}
{$IFDEF ENABLE_LIMIT_CHANNELS_8}
  ENABLE_LIMIT_CHANNELS_8 = True;
{$ELSE}
  ENABLE_LIMIT_CHANNELS_8 = False;
{$ENDIF}
{$IFDEF ENABLE_PNEUMATICS}
  ENABLE_PNEUMATICS = True;
{$ELSE}
  ENABLE_PNEUMATICS = False;
{$ENDIF}
  ENABLE_FAILSAFE_PWD = False;
{$IFDEF ENABLE_CLIENT_MODE}
  ENABLE_CLIENT_MODE = True;
{$ELSE}
  ENABLE_CLIENT_MODE = False;
{$ENDIF}


  // PERM
  {
    ENABLE_SUPPORT_SIGNAL = False;
    ENABLE_FAILSAFE_PWD = False;
    ENABLE_DEBUG_MODE = False;
    ENABLE_LIMIT_CHANNELS_8 = True;
    ENABLE_PNEUMATICS = False;
    ENABLE_AUTH = True; }

implementation

end.
